export NUMBER_OF_CPUS=1
export NUMBER_OF_RAM_MB=2047

touch ~/.no_auto_tmux

apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub
apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/7fa2af80.pub

sudop apt-get install update
sudo apt-get install -y wget python3.9
sudo apt install python3.9-venv
sudo apt-get install -y libpython3.9-dev python3.9-venv libcudnn8
sudo apt update -y
sudo apt install slurmd slurmctld -y
sudo apt install munge vim iproute2 -y
python3.9 -m venv .venv
source .venv/bin/activate
pip install --upgrade pip

sudo chmod 777 /etc/slurm-llnl
sudo cat << EOF > /etc/slurm-llnl/slurm.conf
# slurm.conf file generated by configurator.html.
# Put this file on all nodes of your cluster.
# See the slurm.conf man page for more information.
#
ClusterName=localcluster
SlurmctldHost=localhost
MpiDefault=none
ProctrackType=proctrack/linuxproc
ReturnToService=2
SlurmctldPidFile=/var/run/slurmctld.pid
SlurmctldPort=6817
SlurmdPidFile=/var/run/slurmd.pid
SlurmdPort=6818
SlurmdSpoolDir=/var/lib/slurm-llnl/slurmd
SlurmUser=slurm
StateSaveLocation=/var/lib/slurm-llnl/slurmctld
SwitchType=switch/none
TaskPlugin=task/none
#
# TIMERS
InactiveLimit=0
KillWait=30
MinJobAge=300
SlurmctldTimeout=120
SlurmdTimeout=300
Waittime=0
# SCHEDULING
SchedulerType=sched/backfill
SelectType=select/cons_tres
SelectTypeParameters=CR_Core
#
#AccountingStoragePort=
AccountingStorageType=accounting_storage/none
JobCompType=jobcomp/none
JobAcctGatherFrequency=30
JobAcctGatherType=jobacct_gather/none
SlurmctldDebug=info
SlurmctldLogFile=/var/log/slurm-llnl/slurmctld.log
SlurmdDebug=info
SlurmdLogFile=/var/log/slurm-llnl/slurmd.log
#
# COMPUTE NODES
NodeName=localhost CPUs=${NUMBER_OF_CPUS} RealMemory=${NUMBER_OF_RAM_MB} State=UNKNOWN
PartitionName=LocalQ Nodes=ALL Default=YES MaxTime=INFINITE State=UP
EOF

sudo chmod 755 /etc/slurm-llnl/
sudo service munge start
sudo service slurmd start
sudo service slurmctld start
sudo scontrol update nodename=localhost state=idle
sudo sinfo

git clone https://github.com/facebookresearch/atlas.git
cd atlas
pip install torch==1.11.0 torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu115
pip install faiss-gpu
pip install -r requirements.txt